{
	'name': 'Airbid Master',
	'summary': 'Airbid Master',
	'description': 'Allow to login as supplier and user',
	'version': '14.0.0.1',
	'category': 'website',
	'depends': ['base','website','auth_signup','web','solar_system','mail','contacts','website_sale','product','payment_test','website_google_map','web_widget_image_download','coupon'],
	'data': [
		'security/ir.model.access.csv',
		'views/templates.xml',
		'views/email_verify_otp.xml',
		'views/is_supplier_inherit.xml',
		'views/customer_address_form.xml',
		'views/my_project.xml',
		'views/customer_project_form.xml',
		'views/solar_homepage.xml',
		'views/review_template.xml',
		'views/contact_us_template.xml',
		'views/user_profile.xml',
		'views/project_review_page.xml',
		'views/about_us_template.xml',
		'views/faqs_questation_page.xml',
		'views/supplier_dashboard_template.xml',
		'views/open_supplier_dashboard_template.xml',
		'views/inprogress_supplier_dashboard_template.xml',
		'views/won_supplier_dashboard_template.xml',
		'views/lost_supplier_dashboard_template.xml',
		'views/supplier_dashboard_bid_count.xml',
		'views/supplier_bid_detail_template.xml',
		'views/supplier_membership_template.xml',
		'views/supplier_profile_template.xml',
		'views/supplier_data_detail_template.xml',
		'views/compare_supplier_template.xml',
		'views/how_its_work_page.xml',
		'views/my_account_inherit.xml',
		'views/shop_cart.xml',
		'views/edit_bid_data.xml',
		'views/bid_review_template.xml',
		'data/email_supplier_details_template.xml',
		'views/final_notification_template.xml',
		'views/count_down_time.xml',
		'views/notification_email_template.xml',
		'views/supplier_email_notification.xml',
		'views/installer_supplier_as_customer_dashboard.xml',
		'views/view_customer_address.xml',
		'views/my_solar_panals.xml',
		'views/installer_information.xml',
		'views/create_bid.xml',
		'views/installer_comapre.xml',
		'views/won_installer.xml',
		'views/coupen.xml',
		# 'views/dashboard_as_customer_view.xml',
	],
	# 'demo': [
 #        'demo/product_demo.xml',
 #    ],
	'author': 'Spellbound Soft Solutions',
    'website': 'http://spellboundss.com/',
    'company': 'Spellbound Soft Solutions',
	'auto_install': False,
	'installable': True,
	'application': True,
}