# -*- coding: utf-8 -*-
{
    'name': "Specs - Products",

    'summary': "Configuration of products related to the Specs",
    'author': "Soltein SA de CV",
    'website': "https://www.soltein.mx",
    'contributors': ['Yosbanis Vicente<90yobi90@gmail.com>'],
    'category': 'Uncategorized',
    'version': '17.0.0.1',
    'license': 'LGPL-3',
    'depends': ['product'],
    'data': [
        'security/ir.model.access.csv',
        'views/product_template_views.xml',
        'views/door_family_views.xml',
        'views/door_level_views.xml',
        'views/door_design_views.xml',
        'views/door_suffix_views.xml',
        'views/door_handing_views.xml',
        'views/door_forge_views.xml',
        'views/door_type_glass_views.xml',
        'views/door_traslape_views.xml',
        'views/door_handle_views.xml',
        'views/door_metal_views.xml',
        'views/door_board_type_views.xml',
        'views/door_position_views.xml',
        'views/door_assembly_views.xml',
        'views/door_glass_piece_views.xml',
        'views/door_handing_glass_views.xml',
        'views/door_radius_views.xml',
        'views/product_attribute_views.xml',
        'views/door_accessories_list_views.xml',
        'views/door_configuration_views.xml',
        'views/door_hardware_list_views.xml',
        'views/product_category_views.xml',
    ],
}

