from . import res_partner_inherit
from . import crm_inherit
from . import sale_order_inherit
from . import design_product
from . import account_move_inherit
from . import account_payment_inherit
from . import res_users
from . import mail_thread_inherit
from . import hr_department_inherit
from . import res_company
from . import crm_lead
from . import hr_employee
from . import purchase_order
from . import purchase_order_inherit
from . import ir_http
from . import ir_config_parameter
from . import uom
from . import stock_picking
from . import account_account